name: myislamic
description: تطبيق يخدم المسلمين يساعدهم في عمل الأذكار اليومية الصحيحة وكذلك التأكد من صحة الأحاديث المتداولة واحكام علماء الحديث عليها والبحث في تفاسير القرآن وغيرها من الخدمات.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  share: any
  http: ^0.12.0
  flutter_staggered_grid_view: ^0.2.5
  font_awesome_flutter: ^8.2.0
  # share: ^0.5.3
  flutter:
    sdk: flutter
 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sqflite: any
  path_provider: ^0.4.1
  dio: any

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo_Quran.png
    - assets/logo_Azkar.png
    - assets/logo_hadith.png
    - assets/logo_fatwa.png
    - assets/logo_futrue.png
    - assets/logo_important.png
    - assets/db/Quran.db
    - assets/db/Sunna.db
    - assets/db/Zikr.db
    - assets/images/logo.png
    - assets/images/setting.png
    - assets/images/powered_by.png
    - assets/images/quran.png
    - assets/images/quran2.png
    - assets/images/hadeth.png
    - assets/images/tafseer.jpg
        
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
